// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HE176690ConsoleEFApp.Models;

public partial class Net1810_212_1_ExchangeContext : DbContext
{

    public Net1810_212_1_ExchangeContext() {
    }

    public Net1810_212_1_ExchangeContext(DbContextOptions<Net1810_212_1_ExchangeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<OrderType> OrderTypes { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<UserHave> UserHaves { get; set; }

    public virtual DbSet<UserWant> UserWants { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
=> optionsBuilder.UseSqlServer("Data Source=DESKTOP-574LENG\\HOANGAN;Initial Catalog=Net1810_212_1_Exchange;User ID=sa;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64D8E9D29704");

            entity.ToTable("Customer");

            entity.Property(e => e.Address).HasMaxLength(50);
            entity.Property(e => e.City).HasMaxLength(50);
            entity.Property(e => e.Country).HasMaxLength(50);
            entity.Property(e => e.District).HasMaxLength(50);
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FullName).HasMaxLength(50);
            entity.Property(e => e.Password)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(12)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Order__C3905BCF0A41028A");

            entity.ToTable("Order");

            entity.Property(e => e.Note).HasMaxLength(50);
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.OrderType).WithMany(p => p.Orders)
                .HasForeignKey(d => d.OrderTypeId)
                .HasConstraintName("FK__Order__OrderType__30F848ED");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__OrderDet__D3B9D36CA423D03A");

            entity.ToTable("OrderDetail");

            entity.Property(e => e.Address).HasMaxLength(50);
            entity.Property(e => e.GapPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Message).HasMaxLength(50);
            entity.Property(e => e.Proposer)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__OrderDeta__Order__33D4B598");

            entity.HasOne(d => d.ProductUserHave).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductUserHaveId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Produ__34C8D9D1");

            entity.HasOne(d => d.ProductUserWant).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductUserWantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Produ__35BCFE0A");
        });

        modelBuilder.Entity<OrderType>(entity =>
        {
            entity.HasKey(e => e.OrderTypeId).HasName("PK__OrderTyp__23AC266CC503151D");

            entity.ToTable("OrderType");

            entity.Property(e => e.OrderTypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Product__B40CC6CD31D87B24");

            entity.ToTable("Product");

            entity.Property(e => e.Description).HasMaxLength(100);
            entity.Property(e => e.Img).HasColumnName("img");
            entity.Property(e => e.Origin).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Variation).HasMaxLength(100);

            entity.HasOne(d => d.Customer).WithMany(p => p.Products)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Product__Custome__267ABA7A");
        });

        modelBuilder.Entity<UserHave>(entity =>
        {
            entity.HasKey(e => e.ProductUserHaveId).HasName("PK__UserHave__631B3A50CED46865");

            entity.ToTable("UserHave");

            entity.Property(e => e.Currency).HasMaxLength(10);
            entity.Property(e => e.Description).HasMaxLength(50);
            entity.Property(e => e.GapPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Note).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.UserHaves)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UserHave__Produc__29572725");
        });

        modelBuilder.Entity<UserWant>(entity =>
        {
            entity.HasKey(e => e.ProductUserWantId).HasName("PK__UserWant__24A6779FBDDDE106");

            entity.ToTable("UserWant");

            entity.Property(e => e.Currency).HasMaxLength(10);
            entity.Property(e => e.Description).HasMaxLength(50);
            entity.Property(e => e.GapPrice).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Note).HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.UserWants)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__UserWant__Produc__2C3393D0");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}