// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace Model.Models;

public partial class OrderDetail
{

    public OrderDetail() {
    }
    public int OrderDetailId { get; set; }

    public int OrderId { get; set; }

    public int ProductUserHaveId { get; set; }

    public int ProductUserWantId { get; set; }

    public decimal GapPrice { get; set; }

    public string Proposer { get; set; }

    public int Discount { get; set; }

    public string Message { get; set; }

    public string Address { get; set; }

    public bool? Status { get; set; }
    [JsonIgnore]
    [XmlIgnore]
    public virtual Order Order { get; set; }
    [JsonIgnore]
    [XmlIgnore]
    public virtual UserHave ProductUserHave { get; set; }
    [JsonIgnore]
    [XmlIgnore]
    public virtual UserWant ProductUserWant { get; set; }
}