// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace Model.Models;

public partial class Order
{
    public Order() {
    }

    public int OrderId { get; set; }

    public DateOnly? OrderDate { get; set; }

    public DateOnly? CompleDate { get; set; }

    public int? TotalDiscount { get; set; }

    public int? TotalOrderQuatity { get; set; }

    public string Description { get; set; }

    public decimal TotalPrice { get; set; }

    public string Note { get; set; }

    public bool? UserHaveStatus { get; set; }

    public bool? UserWantStatus { get; set; }
    [JsonIgnore]
    [XmlIgnore]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}