// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace Model.Models;

public partial class Product
{
    public Product() {
    }

    public int ProductId { get; set; }

    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Variation { get; set; }

    public string Price { get; set; }

    public int? Quantity { get; set; }

    public string Origin { get; set; }

    public string Img { get; set; }

    public bool? Status { get; set; }

    [JsonIgnore]
    [XmlIgnore]
    public virtual Customer Customer { get; set; }

    [JsonIgnore]
    [XmlIgnore]
    public virtual ICollection<UserHave> UserHaves { get; set; } = new List<UserHave>();

    [JsonIgnore]
    [XmlIgnore]
    public virtual ICollection<UserWant> UserWants { get; set; } = new List<UserWant>();
}