// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Xml.Serialization;

namespace Model.Models;

public partial class UserWant
{
    public UserWant() {
    }

    public int ProductUserWantId { get; set; }

    public int? ProductId { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public decimal? GapPrice { get; set; }

    public int? Fax { get; set; }

    public string Note { get; set; }

    public DateOnly? CreateDate { get; set; }

    public string Currency { get; set; }

    public int? Quantity { get; set; }

    [JsonIgnore]
    [XmlIgnore]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [JsonIgnore]
    [XmlIgnore]
    public virtual Product Product { get; set; }
}